# Template Matching method names
TEMPLATE_MATCHING_METHOD_TM_CCOEFF = 'cv2.TM_CCOEFF'
TEMPLATE_MATCHING_METHOD_TM_CCOEFF_NORMED = 'cv2.TM_CCOEFF_NORMED'
TEMPLATE_MATCHING_METHOD_TM_CCORR = 'cv2.TM_CCORR'
TEMPLATE_MATCHING_METHOD_TM_CCORR_NORMED = 'CV2.TM_CCORR_NORMED'
TEMPLATE_MATCHING_METHOD_TM_SQDIFF = 'cv2.TM_SQDIFF'
TEMPLATE_MATCHING_METHOD_TM_SQDIFF_NORMED = 'cv2.TM_SQDIFF_NORMED'

# Template Matching option name
TEMPLATE_MATCHING_ON_SINGLE_OBJECT = 'SINGLE'
TEMPLATE_MATCHING_ON_MULTIPLE_OBJECT = 'MULTIPLE'

# Corner Detection method names
HARRIS_CORNER_DETECTION = 'HARRIS_CORNER_DETECTION'
SHI_TOMASI_AND_GOOD_FEATURES_TO_TRACK_CORNER_DETECTION = 'SHI_TOMASI_AND_GOOD_FEATURES_TO_TRACK_CORNER_DETECTION'

# Edge Detection method name
CANNY_EDGE_DETECTION = 'CANNY_EDGE_DETECTION'

# Results
RESULT_NO_MATCH_FOUND = 'NO_MATCH_FOUND'
RESULT_MATCH_FOUND = 'MATCH_FOUND'

# Distance Detection option
DISTANCE_DETECTION_METHOD_CM = 'CM'
DISTANCE_DETECTION_METHOD_MM = 'MM'
DISTANCE_DETECTION_METHOD_IN = 'IN'
DISTANCE_DETECTION_METHOD_PX = 'PX'

# Crop option
CROP_BY_PERCENTAGE = "CROP_BY_PERCENTAGE"
CROP_BY_POINT = "CROP_BY_POINT"

TOOL_PASS = 'PASS'
TOOL_FAIL = 'FAIL'
TOOL_NOT_PROCESS = 'NOT_PROCESS'

# Pixel Tool
PIXEL_COUNT_METHOD_THRESH_BINARY = 'cv2.THRESH_BINARY'
PIXEL_COUNT_METHOD_THRESH_BINARY_INV = 'cv2.THRESH_BINARY_INV'
PIXEL_COUNT_METHOD_THRESH_TRUNC = 'cv2.THRESH_TRUNC'
PIXEL_COUNT_METHOD_THRESH_TOZERO = 'cv2.THRESH_TOZERO'
PIXEL_COUNT_METHOD_THRESH_TOZERO_INV = 'cv2.THRESH_TOZERO_INV'
PIXEL_COUNT_METHOD_ADAPTIVE_THRESH_MEAN_C = "cv2.ADAPTIVE_THRESH_MEAN_C"
PIXEL_COUNT_METHOD_ADAPTIVE_THRESH_GAUSSIAN_C = "cv2.ADAPTIVE_THRESH_GAUSSIAN_C"

# Pixel Tool option name
PIXEL_COUNT_TOOL_ON_BINARY_THRESHOLD = 'BINARY'
PIXEL_COUNT_TOOL_ON_ADAPTIVE_THRESHOLD = 'ADAPTIVE'

IMAGE_PATH = 'D:\\Vision_Application\\hul_bad_230219\\Bad'
