TEMPLATE_MATCHING_METHOD_TM_CCOEFF = 'cv2.TM_CCOEFF'
TEMPLATE_MATCHING_METHOD_TM_CCOEFF_NORMED = 'cv2.TM_CCOEFF_NORMED'
TEMPLATE_MATCHING_METHOD_TM_CCORR = 'cv2.TM_CCORR'
TEMPLATE_MATCHING_METHOD_TM_CCORR_NORMED = 'CV2.TM_CCORR_NORMED'
TEMPLATE_MATCHING_METHOD_TM_SQDIFF = 'cv2.TM_SQDIFF'
TEMPLATE_MATCHING_METHOD_TM_SQDIFF_NORMED = 'cv2.TM_SQDIFF_NORMED'

TEMPLATE_MATCHING_ON_SINGLE_OBJECT = 'SINGLE'
TEMPLATE_MATCHING_ON_MULTIPLE_OBJECT = 'MULTIPLE'

HARRIS_CORNER_DETECTION = 'HARRIS_CORNER_DETECTION'
SHI_TOMASI_AND_GOOD_FEATURES_TO_TRACK_CORNER_DETECTION = 'SHI_TOMASI_AND_GOOD_FEATURES_TO_TRACK_CORNER_DETECTION'

CANNY_EDGE_DETECTION = 'CANNY_EDGE_DETECTION'


RESULT_NO_MATCH_FOUND = 'NO_MATCH_FOUND'
RESULT_MATCH_FOUND = 'MATCH_FOUND'