# Template Matching method names
TEMPLATE_MATCHING_METHOD_TM_CCOEFF = 'cv2.TM_CCOEFF'
TEMPLATE_MATCHING_METHOD_TM_CCOEFF_NORMED = 'cv2.TM_CCOEFF_NORMED'
TEMPLATE_MATCHING_METHOD_TM_CCORR = 'cv2.TM_CCORR'
TEMPLATE_MATCHING_METHOD_TM_CCORR_NORMED = 'CV2.TM_CCORR_NORMED'
TEMPLATE_MATCHING_METHOD_TM_SQDIFF = 'cv2.TM_SQDIFF'
TEMPLATE_MATCHING_METHOD_TM_SQDIFF_NORMED = 'cv2.TM_SQDIFF_NORMED'

# Template Matching option name
TEMPLATE_MATCHING_ON_SINGLE_OBJECT = 'SINGLE'
TEMPLATE_MATCHING_ON_MULTIPLE_OBJECT = 'MULTIPLE'

# Corner Detection method names
HARRIS_CORNER_DETECTION = 'HARRIS_CORNER_DETECTION'
SHI_TOMASI_AND_GOOD_FEATURES_TO_TRACK_CORNER_DETECTION = 'SHI_TOMASI_AND_GOOD_FEATURES_TO_TRACK_CORNER_DETECTION'

# Edge Detection method name
CANNY_EDGE_DETECTION = 'CANNY_EDGE_DETECTION'

# Results
RESULT_NO_MATCH_FOUND = 'NO_MATCH_FOUND'
RESULT_MATCH_FOUND = 'MATCH_FOUND'

# Distance Detection option
DISTANCE_DETECTION_METHOD_CM = 'CM'
DISTANCE_DETECTION_METHOD_MM = 'MM'
DISTANCE_DETECTION_METHOD_IN = 'IN'
DISTANCE_DETECTION_METHOD_PX = 'PX'

#Crop option
CROP_BY_PERCENTAGE = "CROP_BY_PERCENTAGE"
CROP_BY_POINT = "CROP_BY_POINT"

TOOL_PASS = 'PASS'
TOOL_FAIL = 'FAIL'