import enum


class ToolType(enum.Enum):
    TEMPLATE_MATCHING = 'TEMPLATE_MATCHING'
    EDGE_DETECTION = 'EDGE_DETECTION'
    CONTOUR_DETECTION = 'CONTOUR_DETECTION'
    CORNER_DETECTION = 'CORNER_DETECTION'
    DISTANCE_DETECTION = 'DISTANCE_DETECTION'
    ANGLE_DETECTION = 'ANGLE_DETECTION'
    CROP = 'CROP'
    NO_TOOL = 'NO_TOOL'
